# Generated by Django 5.0.7 on 2024-11-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('employee', 'Employee'), ('admin', 'Admin')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
