# Generated by Django 5.0.7 on 2024-08-02 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoVehiculo', models.CharField(choices=[('0', 'chata'), ('1', 'auto'), ('2', 'moto'), ('3', 'cuatri')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='FichasTecnicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('0', '2'), ('1', '3'), ('2', '4'), ('3', '5')], max_length=1, null=True)),
                ('cilindradas', models.CharField(max_length=50)),
                ('combustible', models.CharField(choices=[('0', 'electricidad'), ('1', 'nafta'), ('2', 'diesel'), ('3', 'gas')], max_length=1, null=True)),
                ('paisFabrica', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Modelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50, verbose_name='Nombre del modelo')),
                ('año', models.DateField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.categorias')),
                ('fichaTecnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.fichastecnicas')),
                ('marcas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.marcas')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('km', models.PositiveIntegerField()),
                ('detalles', models.CharField(max_length=50, null=True)),
                ('precio', models.PositiveIntegerField()),
                ('compra', models.PositiveIntegerField(null=True, verbose_name='precio compra')),
                ('venta', models.PositiveIntegerField(verbose_name='precio venta')),
                ('disponibilidad', models.BooleanField(null=True)),
                ('modelos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.modelos')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.proveedor')),
            ],
        ),
    ]
