# Generated by Django 5.0.7 on 2024-08-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichastecnicas',
            name='puertas',
            field=models.CharField(blank=True, choices=[('0', '2'), ('1', '3'), ('2', '4'), ('3', '5')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='modelos',
            name='año',
            field=models.DateField(),
        ),
    ]
