# Generated by Django 5.0.7 on 2024-11-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_alter_fichastecnicas_puertas_alter_modelos_año'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='portada',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
