# Generated by Django 5.0.7 on 2024-08-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_alter_fichastecnicas_puertas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelos',
            name='año',
            field=models.DateField(),
        ),
    ]
