# Generated by Django 5.0.7 on 2024-08-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='puesto',
            field=models.CharField(choices=[('0', 'VENDEDOR'), ('1', 'ADMINISTRADOR'), ('2', 'USUARIO'), ('3', 'GERENTE')], max_length=1),
        ),
    ]
