# Generated by Django 5.0.7 on 2024-08-05 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('medioPago', models.CharField(choices=[('0', 'efectivo'), ('1', 'tarjeta')], max_length=1)),
                ('cuotas', models.CharField(choices=[('0', '1'), ('1', '3'), ('2', '6'), ('3', '12')], max_length=1)),
                ('interes', models.PositiveIntegerField()),
                ('montoFinanciado', models.PositiveIntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.usuarios')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.empleados')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehiculo')),
            ],
        ),
    ]
